### ISSUE TITLE
Can offending parameter be named?

### ISSUE THREAD

**Issue by PeterEmanuel** [Tracktion/pluginval#100]
If an issue is found, for instance with "Parameters not restored on setStateInformation", you get a message that "a" parameter was out of range.

Is it please possible to add its name to that line? I assume it is available at that point in Pluginval?
That would be real time saver!

Thanks for this great tool!

Peter

**Comment by drowaudio** [comment]
If you could add a PR that would be a real time saver! It's ADC this week so we're all slammed with that.

**Comment by PeterEmanuel** [comment]
First, enjoy ADC!

But, a PR for this, I am sorry. I am focusing on support for an AUval rejection and in a big hurry.

Debugging this testing code, I find that it is **not** doing what the messages might suggest, but:

- It calculates a deviation between a stored state and a manipulated one. 
- That could make sense, if it were not for the fact that it uses parameter value **sums** and compares them with a fixed value 0.1f.
- This means that you can make this test fail by simply adding more parameters. And parameters with very small values will not be sum as fast as ones with larger values...
- That deviation should at least be divided (normalized) by the number of parameters. And comparing a sum with 0.1 seems a bit too arbitrary to me.

If there is a single offending parameter, it will not log that, like I reported.
But that would just be so much more helpful!

If you store the parameter values locally in a vector in this method, before and after randomizing them, the test could simply report the misbehaving parameter. Or just dump all their values, before and after.

Again, also sorry that I cannot do a PR. My coding style is also quite different and we would start discussions on such non-relevant things - I really do not have any time at the moment - like you, now at ADC (teasing only!)

Best regards,

Peter

**Comment by drowaudio** [comment]
Fixed here: https://github.com/Tracktion/pluginval/pull/101
