### ISSUE TITLE
AAX Hosting

### ISSUE THREAD

**Issue by moritzsur** [Tracktion/pluginval#103]
I think it would be great to test AAX plugins from pluginval as well, but is that even possible? 
Maybe only the aax validator could be included?
I would love to test some of this stuff but there seems to be an issue with the aax validator download on the avid website...

**Comment by drowaudio** [comment]
That would be the only way to do it but I don't know if we're allowed to redistribute the AAX validator.

As juce can't host AAX plugins there's not much benefit over just running the AAX validator as part of your own CI.

**Comment by moritzsur** [comment]
Got it!
What about adding more default samplerates and blocksizes on strictness 10 to come closer to aax requirements?

**Comment by drowaudio** [comment]
What combinations would you like to see added?

**Comment by moritzsur** [comment]
Blocksizes: 32, 64, 128, 256, 512, 1024
Samplerates: 44.1kHz, 48kHz, 88.2kHz, 96kHz and 192kHz

**Comment by moritzsur** [comment]
And a lot of people use blocksizes of 2048 when they are not in a recording environment

**Comment by drowaudio** [comment]
I'm not actually sure this is a good idea. It's going to make running the tests twice as long for everybody.
You know you can specify the samples rates and block sizes to test on the command line? Would this be suitable for you?
It would be a pain to add more defaults just for strictness level 10 due to the way parsing happens.

**Comment by moritzsur** [comment]
Yes I just thought about making the last strictness really cover everything, but the current state is completely fine by me :)
