### ISSUE TITLE
Would it be possible to catch JUCE assertions in pluginval?

### ISSUE THREAD

**Issue by moritzsur** [Tracktion/pluginval#110]
In my case, a colour in the laf was missing:
`-----------------------------------------------------------------
Starting tests in: pluginval / Editor Automation...
JUCE Assertion failure in juce_LookAndFeel.cpp:85`
...
`*** All tests completed successfully! ***`

What would be the best way to implement this in pluginval?

**Comment by drowaudio** [comment]
Is your plugin built in debug mode?
If so, can you define assertions to terminate? They'll be caught as crashes (with stack traces) then.

**Comment by moritzsur** [comment]
I separated my CI/CD now into a test and a deploy workflow with pluginval running in both to test the debug and release builds.
