### ISSUE TITLE
test multiple plugins with one call

### ISSUE THREAD

**Issue by umlaeute** [Tracktion/pluginval#115]
Would it be possible to specify multiple plugins on the cmdline?

e.g.
```sh
./pluginval --validate plug1.so plug2.so
```

rather than
```sh
./pluginval --validate plug1.so
./pluginval --validate plug2.so
```

**Comment by drowaudio** [comment]
No sorry, I used to support that but it was too confusing and running them separately is much cleaner.
It also means you can run them in parallel with bash using `&` if you want to.

**Comment by umlaeute** [comment]
> No sorry, I used to support that but it was too confusing and running them separately is much cleaner.

fair enough.
you might want to add the fact that you don't support testing multiple plugins together and the reasoning why to some (visible) documentation.

>  It also means you can run them in parallel with bash using & if you want to.

well, i could also run multiple tests (with one plugin each) in parallel by using background jobs, if `pluginval` supported testing multiple plugins in one call; so that does not seem to be a valid argument.

**Comment by drowaudio** [comment]
It's not quite the same though as when running them in the same process they'll share a message thread and memory etc.

I don't think there's anything that suggests you _can_ run multiple plugins simultaneously though is there? I don't really want to get in to the habit of adding documentation for everything it can't do. But I agree it should probably fail command line parsing if there are more arguments after the plugin path and say it can only process one at a time.

**Comment by umlaeute** [comment]
> It's not quite the same though as when running them in the same process they'll share a message thread and memory etc.

you are totally right.
i probably misunderstood the "it also means" part to say that "it's a unique feature of only allowing a single plugin to be tested, that you can run multiple tests in parallel by adding a `&` at the end".
i guess you just wanted to say "you can do something like this anyhow, using your system's parallelization powers"

> it should probably fail command line parsing if there are more arguments after the plugin path

:+1:
