### ISSUE TITLE
explicitly encode success in output

### ISSUE THREAD

**Issue by umlaeute** [Tracktion/pluginval#118]
`./pluginval` returns the success of a test in it's exit code. nice!

however, when testing many plugins in our CI, we find this a bit cumbersome, as we do not want to stop testing after the first failed test.

We end up having to record the success/failure manually with something like:
```sh
find VST2/ -name "*.vst2" -o -name "*.so" | while read fname; do
  ./pluginval --validate-in-process --strictness-level 10 --repeat 3 --skip-gui-tests --output-dir test-logs/ "$fname" || echo "${fname} failed with exit code $?" >> failed-tests.txt
done
find VST3/ -name "*.vst3" | while read fname; do
  ./pluginval --validate-in-process --strictness-level 10 --repeat 3 --skip-gui-tests --output-dir test-logs/ "$fname" || echo "${fname} failed with exit code $?" >> failed-tests.txt
done
# fail if we recorded some failed test
test ! -f failed-tests.txt
```

Now I would like to suggest to just add a last line to the output that indicates the success: `SUCCESS` resp `FAILURE`.

thus we could reduce our logic to:
```sh
find VST2/ -name "*.vst2" -o -name "*.so" -exec ./pluginval --validate-in-process --strictness-level 10 --repeat 3 --skip-gui-tests --output-dir test-logs/  {} ";"
find VST3/ -name "*.vst3"                 -exec ./pluginval --validate-in-process --strictness-level 10 --repeat 3 --skip-gui-tests --output-dir test-logs/  {} ";"
# fail if there's at least one logfile that does not end with 'SUCCESS'
! find test-logs -type f -exec tail -1 {} ";" | grep -v "^SUCCESS$"
```

(it's obviously not enough to test for `FAILURE` in case a plugin crashes the validator)

**Comment by drowaudio** [comment]
Yes, that could be added.

I think a more general approach would be to add junit output formatting. I've got some code that does this but it needs implementing in pluginval: https://github.com/Tracktion/tracktion_engine/blob/80aeaf352fa92e95dfd1a3c6182c05269bd26cd4/examples/TestRunner/TestRunner.h#L105
