### ISSUE TITLE
Failed assertion in createDestinationFileStream() with "Validate in process" checked

### ISSUE THREAD

**Issue by jamiebullock** [Tracktion/pluginval#13]
If I build pluginval from source using 97dfa54bccfeeeac0b45ff6f12cdb3d3a400b167 it works fine with with "Validate in process" disabled. However if I enabled "Validate in process" I get an assertion failure at: Validator.cpp:159

```
std::unique_ptr<FileOutputStream> createDestinationFileStream (PluginTests& test)
{
    std::unique_ptr<FileOutputStream> fos (getDestinationFile (test).createOutputStream());

    if (fos && fos->openedOk())
        return fos;

    jassertfalse;    // <------ HERE
    return {};
}
```

I think it is because the test options are not getting populated for some reason.

I get the problem with any plugin I attempt to test. 

I am only testing AU plugins on macOS 10.14.3

**Comment by jamiebullock** [comment]
Update: I only get the problem with the built-from-source pluginval. If I use the latest binary release I do not get the problem. However, I need the source build so I can set `testRunner.setAssertOnFailure (true);`

**Comment by drowaudio** [comment]
Hmm, looks like that assertion is a mistake.
Presumably you haven't specified any file to log to on the command line?

**Comment by jamiebullock** [comment]
@drowaudio nope. I think the reason release builds work and debug doesn't is simply the absence of the assertion in the release builds. Commenting out the assertion in debug, everything works fine.

**Comment by jamiebullock** [comment]
Great work with pluginval BTW. Super-useful tool 👍🏻

**Comment by drowaudio** [comment]
Does this fix it for you?
https://github.com/Tracktion/pluginval/commit/3b77bccde4f381bb5721c8be227153098b8ca4c3

**Comment by jamiebullock** [comment]
Yup, that fixes it for me. Thanks!
