### ISSUE TITLE
Download links are broken since v1.0.4

### ISSUE THREAD

**Issue by nickdowell** [Tracktion/pluginval#139]
The following download links are broken since the v1.0.4 release was published:

- https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_Windows.zip
- https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_macOS.zip
- https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_Linux.zip

**Comment by drowaudio** [comment]
@sudara did something go wrong with the release? It doesn't look like any binaries were added to it?
I thought that was automatic?

**Comment by sudara** [comment]
Yes, I also noticed this late last night, looks like the `download-artifact` version is mismatched from the upload, fixing now.

**Comment by sudara** [comment]
Re-released 1.0.4, sorry about the turbulence!
