### ISSUE TITLE
macOS binary fails on AU formats

### ISSUE THREAD

**Issue by ryerson** [Tracktion/pluginval#15]
I'm running macOS Mojave 10.14.4, and I've been seeing failures when testing AU formats. When I execute the binary directly (per the [CI instructions](https://github.com/Tracktion/pluginval/blob/master/docs/Adding%20pluginval%20to%20CI.md)) pluginval is unable to find any AU plugins: 
```
$ ~/Downloads/pluginval.app/Contents/MacOS/pluginval --validate ~/Library/Audio/Plug-Ins/Components/ --output-dir ~/logs/

...

Num types found: 0
!!! Test 1 failed: No types found
FAILED!!  1 test failed, out of a total of 1
```
It also fails to find AUs when I take away the args and launch the GUI.

These errors don't occur when I use the `open` command to launch the application:
```
$ open ~/Downloads/pluginval.app --args --validate ~/Library/Audio/Plug-Ins/Components/ --output-dir ~/logs/
```

Are there environment variables, or any other state that need to be set in order to run the binary directly?

Additional info:
As far as I can tell, VST and VST3 are not affected by this issue. I've observed this issue with the pluginval v0.2.3 binary downloaded from github as well as a version built locally.

**Comment by drowaudio** [comment]
This argument doesn't look right to me: `--validate ~/Library/Audio/Plug-Ins/Components/`
You're not actually giving it a plugin file to validate. It should be something like `--validate ~/Library/Audio/Plug-Ins/Components/MyPlugin.component`

**Comment by ryerson** [comment]
My understanding was that the `--validate` argument is effectively a recursive search path. When I use the `open` technique, it correctly finds all the AU plugins in that directory, and this also works when I pass the VST and VST3 directories.

That said, I've observed this same error when specifying the exact path of individual plugins.

**Comment by ryerson** [comment]
I just discovered that I can only reproduce this bug when I run the binary from within a tmux session. This gives me a workaround, but I'd still appreciate any insight you have as to what's causing the issue. I compared the shell environments between a normal terminal session and a tmux session, and the differences seem to be negligible:
```
$ diff /tmp/base_term /tmp/tmux_term
1,2c1,2
< TERM=xterm-256color
< SHLVL=1
---
> TERM=screen-256color
> SHLVL=2
```

**Comment by cjappl** [comment]
Hi @ryerson, ran into this same issue running auval, I suspect they are related:
https://github.com/tmux/tmux/issues/1847

Basically the state of things right now is tmux is pointing fingers and apple and vice versa. Keep an eye on that issue for any movement, I contacted someone at Apple but I wouldn't really hold my breath...

**Comment by drowaudio** [comment]
Ok, this should be fixed on develop now here: https://github.com/Tracktion/pluginval/commit/28a4a9db1b39067337494194b63fcf7811aff20c

**Comment by cjappl** [comment]
For the record, I don't think that commit fixed this particular issue.

This issue has to do with tmux being a pain right now, so this is properly closed for pluginval! It just isn't an issue that falls under pluginval's domain

**Comment by ryerson** [comment]
Thanks for the info!
