### ISSUE TITLE
VS2015 compat

### ISSUE THREAD

**Issue by joaorossi** [Tracktion/pluginval#16]
Due to our build requirements, I can only use VS2015.
I could make it build clean just by adding a ctor to PluginTest::Requirements

**Comment by drowaudio** [comment]
Hmm, I don't really want to have to support pre-C++14 compilers.
Can you perhaps explain what the use case it and why it's not possible to use a newer version or if it's part of CI just a different version of the BuildTools?

**Comment by joaorossi** [comment]
That makes sense...
Our main problem is the AAX SDK, which recently started supporting VS2015, and our anti-piracy system, which also keep us locked in VS2015.
The only motivation for this is that we don't even have VS2017 installed on our build box.
But I can easily build it somewhere else. Since it was so easy to get it to build, I just wanted to give a friendly nudge :)

**Comment by drowaudio** [comment]
Ok. I'll see if I can add that. I just fear this will be a pain to maintain as I don't have it building on VS2015.

VS2015 is ABI compatible with VS2017 so you can use the same AAX libs I think (and probably your anti-piracy libs), although we build the AAX libs as part of our CI so they're build with the same compiler.

Alternatively you should just be able to download the pre-built binaries from GitHub. That's what we do on our build server. I only build locally if I'm debugging a pluginval failure.
