### ISSUE TITLE
[FR] Windows: Update .bat to check if Projucer is built first

### ISSUE THREAD

**Issue by jrlanglois** [Tracktion/pluginval#17]
As per the [docs](https://github.com/Tracktion/pluginval#windows), there's a subtle requirement on the Projucer being built from the submodule. This means the `.bat` file fails immediately and closes the Command Prompt, so you won't ever found out _why_ it failed at all.

It would be good to trigger an error message if the Projucer binary doesn't exist beforehand.

**Comment by drowaudio** [comment]
The toolchain has changed with 1.0.0 so the PJ isn't needed at all now
