### ISSUE TITLE
Host validation ?

### ISSUE THREAD

**Issue by jcelerier** [Tracktion/pluginval#2]
The doc says "It is designed to be used by both plugin and host developers" : does it mean that there is a way to run pluginval itself as a plug-in and have it stress-test a host ? 

Thanks for the great work in any case, it is extremely useful !

**Comment by drowaudio** [comment]
Unfortunately not, although that would be cool...

The main place we use this as a host developer is to find out what kinds of things plugins are doing to "violate" validation so we can contact plugin developers to inform them and, as a last resort, add work-arounds in the host for specific plugins.

The main feature that's useful for host developers is the ability to validate lots of plugins at once (and even have users do this if getting NRFs/demos is difficult). As a host developer, you could build a CI machine with lots of plugins installed and periodically validate them with `pluginval` which should tell you when compatibility changes etc. (or you could have QA do this). This is much quicker than loading all the plugins in to your host and trying to test all the things pluginval does with it (automation, busses, setting all parameters, multiple buffer/block sizes etc. spring to mind as time-consuming tasks).

It's not a silver bullet but it aims to improve the speed at which you can get information about host <-> plugin compatibility.

I hope that helps!

**Comment by jcelerier** [comment]
thanks, indeed that's how I started using it. I am interested in writing an "host" validator - I'll keep you posted if I get around writing one at some point.
