### ISSUE TITLE
Validation of aaxplugins

### ISSUE THREAD

**Issue by vallant** [Tracktion/pluginval#22]
Hi- first of all thank you for the very nice app, it's a fixed part of my development routine :)

I'd just wanted to ask if there are plans to add the possibility of compiling support for aax plugins too? As you can manually compile the support for vst2 as well (and JUCE itself does support it as well), i think this should be possible in theory, right?

Thanks a lot anyways!

**Comment by drowaudio** [comment]
Hi there, unfortunately no one apart from Avid are able to host AAX plugins so we can't offer this capability.
