### ISSUE TITLE
Validation of LV2 plugins?

### ISSUE THREAD

**Issue by mxmilkiib** [Tracktion/pluginval#25]

**Comment by drowaudio** [comment]
I only support validation of plugin formats supported by JUCE hosting I'm afraid.
So when JUCE gains hosting support of LV2 I'll happily add this, it's not really possible until that point I'm afraid.

**Comment by mxmilkiib** [comment]
JUCE 7 now comes with LV2 support.

**Comment by falkTX** [comment]
v1.0.0 does not have LV2, maybe something for v1.1.0 ?

**Comment by drowaudio** [comment]
Yes, I haven't added LV2 support yet for a couple of reasons:

- LV2 support is pretty new to JUCE and I wanted to give it time to settle down before adding validation via JUCE (there are a few JUCE forum posts still discussing some of the finer points of LV2 hosting)
- I'm not very familiar with LV2 hosting so it would be difficult for me to ensure the validation is actually doing the correct thing

I'm sure it will get added in time. Someone could always open a PR...
