### ISSUE TITLE
ValueTree::toXmlString() does not support objects

### ISSUE THREAD

**Issue by aurelium** [Tracktion/pluginval#29]
I get an assertion when running pluginval in Debug mode: ValueTree can't handle the options.disabledTests, which seems to be kept as an object. It is probably better to pass this as a String with tokens rather than a StringArray?

For now, commenting out this line in Validator.cpp removes the assertion:
`v.setProperty (IDs::disabledTests, options.disabledTests, nullptr);`

**Comment by drowaudio** [comment]
Thanks, this should be fixed now.
