### ISSUE TITLE
Linux Mint 19 Build Fail

### ISSUE THREAD

**Issue by davidhealey** [Tracktion/pluginval#3]
Hi,

I tried running the Linux Build you provide but get this message
`/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found`

So I tried building from source following your instructions and hit this

`Compiling include_juce_gui_extra.cpp
In file included from /usr/include/webkitgtk-4.0/webkit2/webkit2.h:54:0,
                 from ../../../../modules/juce_gui_extra/juce_gui_extra.cpp:117,
                 from ../../JuceLibraryCode/include_juce_gui_extra.cpp:9:
/usr/include/webkitgtk-4.0/webkit2/WebKitJavascriptResult.h:28:10: fatal error: jsc/jsc.h: No such file or directory
 #include <jsc/jsc.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:449: recipe for target 'build/intermediate/Release/include_juce_gui_extra_6dee1c1a.o' failed
make: *** [build/intermediate/Release/include_juce_gui_extra_6dee1c1a.o] Error 1
`

**Comment by drowaudio** [comment]
Thanks @davidhealey, I've just pushed a change to develop that should remove the dependancy on cURL. https://github.com/Tracktion/pluginval/commit/20c00b99cf7091df1ad0c0bc40349cb040131ae9

Can you try grabbing the tip, rebuilding and seeing if that version runs please?
Cheers,
Dave

**Comment by drowaudio** [comment]
Sorry @davidhealey, I missed this.
What is giving you messages about licences? Is this the Projucer?

How are you building `pluginval`? Manually or by using one of the build scripts?
Are you able to build it in GPL mode? That should get rid of the licencing requirements.

**Comment by davidhealey** [comment]
Hi,

I couldn't remember how I generated the error so I decided to start again from scratch. Using the build script Projucer builds just fine but when it moves on to build the app I get this:

```
Compiling include_juce_audio_processors.cpp
In file included from ../../modules/juce/modules/juce_audio_processors/juce_audio_processors.cpp:164:0,
                 from ../../JuceLibraryCode/include_juce_audio_processors.cpp:9:
../../modules/juce/modules/juce_audio_processors/format_types/juce_LADSPAPluginFormat.cpp:29:10: fatal error: ladspa.h: No such file or directory
 #include <ladspa.h>
```

**Comment by drowaudio** [comment]
Yes, LADSPA is turned on by default. You can get this to compile easily by installing the package with `sudo apt-get install ladspa-sdk`
