### ISSUE TITLE
Way to figure out where an allocation in a real time thread occurs?

### ISSUE THREAD

**Issue by cjappl** [Tracktion/pluginval#30]
I'm wondering if there is a breakpoint, or logging to enable where in my code base an illegal allocation is occurring. It appears I'm being a bad citizen and allocating in a real time thread:

-----------------------------------------------------------------
Starting test: pluginval / Allocations during process...
Testing with sample rate [44100] and block size [64]
!!! Test 1 failed: Allocations occured in audio thread: 36
!!! Test 5 failed: Allocations occured in audio thread: 18
!!! Test 9 failed: Allocations occured in audio thread: 20
!!! Test 13 failed: Allocations occured in audio thread: 22
!!! Test 17 failed: Allocations occured in audio thread: 18
!!! Test 21 failed: Allocations occured in audio thread: 18
!!! Test 25 failed: Allocations occured in audio thread: 20
!!! Test 29 failed: Allocations occured in audio thread: 18
!!! Test 33 failed: Allocations occured in audio thread: 18
!!! Test 37 failed: Allocations occured in audio thread: 18
Testing with sample rate [44100] and block size [128]
!!! Test 41 failed: Allocations occured in audio thread: 34
!!! Test 45 failed: Allocations occured in audio thread: 18
!!! Test 49 failed: Allocations occured in audio thread: 18
!!! Test 53 failed: Allocations occured in audio thread: 18
!!! Test 57 failed: Allocations occured in audio thread: 18
!!! Test 61 failed: Allocations occured in audio thread: 18
!!! Test 65 failed: Allocations occured in audio thread: 18
!!! Test 69 failed: Allocations occured in audio thread: 20
!!! Test 73 failed: Allocations occured in audio thread: 18
!!! Test 77 failed: Allocations occured in audio thread: 18

Any idea on the fastest way to determine where these are happening to track them down?

**Comment by drowaudio** [comment]
There's a document that describes the best way to do this here: https://github.com/Tracktion/pluginval/blob/develop/docs/Debugging%20a%20failed%20validation.md

For debugging allocations you probably want to follow this process but put a break point here: https://github.com/Tracktion/pluginval/blob/3b1adf324c1b1d31866992cb6d74642199fe6d91/Source/TestUtilities.cpp#L74

**Comment by cjappl** [comment]
Hmm, I never hit that line in my debugger when this problem occurs, is there another option I need to turn on besides validate in process?

**Comment by drowaudio** [comment]
If you validate the plugin in-process. Do you still see the allocation errors?

There’s another place this warning gets logged, for arrays a few lines down. Perhaps it’s that one that’s being triggered?

**Comment by cjappl** [comment]
Ah, got it. User error. Your instructions above were sufficient! 

Thanks so much for the help :)
