### ISSUE TITLE
Chocolatey support available

### ISSUE THREAD

**Issue by Xav83** [Tracktion/pluginval#35]
Hi Pluginval devs,

I don't know where to put this information, so I put it here.
I have created a chocolatey package with the [last version of pluginval](https://github.com/Tracktion/pluginval/releases/tag/v0.2.6).

I will continue to maintain this package when new version of pluginval are going to come up :)

Is there a place in the documentation to specify this ? (it can be very useful for CI tests, for example)

**Comment by drowaudio** [comment]
HI there, thanks for doing this. Sure, if you can give me some additions to the README or maybe one of the docs I can add that.

Can I ask what the process for creating the chocolatey package is? It might be something I can add to the CI build process?

**Comment by Xav83** [comment]
Hi @drowaudio ! 🙂 

For the documentation, I am going to create a Pull Request. It will be simpler that way, I think 😉 

For the chocolatey package creation process, I don't know if there is a way to integrate it to an already existing CI build process.

Personally, I am using the Automatic Packaging Framework of chocolatey named [AU](https://github.com/majkinetor/au/blob/master/README.md). This framework is setup so that a check on every packages I maintain occurs regularly (trigger by a cron job), and if a new version is found, then, a new version of the chocolatey package is created, sent to chocolatey package database where it will be tested automatically, and after that, a human moderator will validate the new version of the chocolatey package and make it fully available.

If you want, I can add you and/or other persons to the [Github repository](https://github.com/Xav83/chocolatey-packages/tree/develop/automatic/pluginval) where I maintain pluginval chocolatey packages, and to the official maintainers of the [chocolatey package websire of pluginval](https://chocolatey.org/packages/pluginval)

**Comment by Xav83** [comment]
@drowaudio I created a pull request with the informations that, I think should be added.
Feel free to modify it before integrate it to develop 😉

**Comment by drowaudio** [comment]
Thanks! I've merged that now.
