### ISSUE TITLE
AudioUnit MIDI effects plugins (aumi) not validated

### ISSUE THREAD

**Issue by aurelium** [Tracktion/pluginval#38]
For MIDI effects AU plugins (aumi), "Test 1 failed: No types found" is returned.

If pluginval is unable to assess these, it should show a warning and proceed (with success). It's cumbersone to make build scripts distinguish between different plugin types. pluginval should be more tolerant here, IMHO, or support the type.

**Comment by drowaudio** [comment]
Are you sure those types aren't found and this isn't just a problem with the AU component registrar?
I can't think of any reason why the scanning would omit them unless there's a problem with the JUCE plugin scanning?

**Comment by aurelium** [comment]
I thought the benefit of pluginval was to be able to test plugins that are not necessarily installed.
Does validation require all plugins to be installed in /Library/Audio/Plug-Ins/Components ?

**Comment by aurelium** [comment]
Update: Had to move the unit out of and back into /Library/Audio/Plug-Ins/Components for this to work again.
I see how this is Apple's fault, but being unable to validate AudioUnits without installing them is not very useful.

**Comment by drowaudio** [comment]
Agreed. Unfortunately this isn't something we have control over. You can only load an AU by identifier and you have to ask the OS for it. This means it needs to be installed in the "Components" directory.

Usually, on build systems you'd do this install as part of the build process, restart the AU Component Registrar with `killall -9 AudioComponentRegistrar` and then hope the OS gives you an instance when you ask for it.

VST2 and VST3 can be validated using a path though.

**Comment by aurelium** [comment]
Thanks for the killall hint. Very helpful!
