### ISSUE TITLE
"Test File" function seems to have stopped working since Win10 "20H2"

### ISSUE THREAD

**Issue by rexmartin158** [Tracktion/pluginval#47]
I have used the "Test File" function many times in the past but it no longer does anything in Win10 - I believe since 20H2.  Scanning plugin folders brings up the list - so plugin val can still be used - but sometimes during plugin development it's convenient to access the file directly in the build folder (using the "Test File" button).

Other Apps - like Wavelab 9 - also have issues with file manager since 20H2 - must be similar problem here.

**Comment by drowaudio** [comment]
Ok, that is odd. Are you using the released builds or building from scratch?
If you're building from scratch can you try updating JUCE and see if that helps? It might be something that has been resolved there.

**Comment by rexmartin158** [comment]
> 
> 
> Ok, that is odd. Are you using the released builds or building from scratch?

This is with the latest release build (v0.2.9)

**Comment by drowaudio** [comment]
I've got a draft 0.3.0 release here now: https://github.com/Tracktion/pluginval/releases/tag/untagged-5355f0994ed2d4b76f9e
If you download the Windows build from there does that work correctly?

**Comment by rexmartin158** [comment]
> 
> 
> I've got a draft 0.3.0 release here now: https://github.com/Tracktion/pluginval/releases/tag/untagged-5355f0994ed2d4b76f9e
> If you download the Windows build from there does that work correctly?

That link gives a  "404" error and when opened directly from the Releases folder I don't see a Windows build in either of the compressed folders.

**Comment by drowaudio** [comment]
Sorry, I had to publish it to make it visible. You should be able to find the links here now: https://github.com/Tracktion/pluginval/releases/tag/v0.3.0

**Comment by sudara** [comment]
I was able to reproduce this problem on 20H2: Clicking the "Test File" button brings up the file browser, but selecting a file results in only the pluginval/JUCE version being printed to Console and no actual validations being run.

The 0.3.0 release fixes it on my machine.

**Comment by drowaudio** [comment]
Great. I'll wait for verification from @rexmartin158 and then publish this as a full release.
Thanks!

**Comment by rexmartin158** [comment]
> 
> 
> Great. I'll wait for verification from @rexmartin158 and then publish this as a full release.
> Thanks!

Yes, v0.3.0 is working here again!  Thank you!

So was this due to 20H2?  If so, what did Microsoft do that caused it?  (As I mentioned in the OP here other apps are having trouble too - wondering why)

**Comment by drowaudio** [comment]
I think it was a change in JUCE that wasn't compatible with the latest Windows version but I'm not 100% sure.
