### ISSUE TITLE
Downloading "latest_release" does not actually download the latest release

### ISSUE THREAD

**Issue by jatinchowdhury18** [Tracktion/pluginval#51]
The documented examples for running pluginval as part of a CI pipeline show scripts for downloading pluginval from a GitHub release link to the "latest_release" (see [here](https://github.com/Tracktion/pluginval/blob/develop/docs/Adding%20pluginval%20to%20CI.md#examples)). Unfortunately, when downloading pluginval from this link and trying to run it, the console output shows that I'm actually running v0.2.7, rather than v0.3.0 which is technically the actual "latest release".

Not sure if there's something weird happening with the GitHub release, or if the documentation just needs to be updated, but I thought I'd mention it here.

**Comment by drowaudio** [comment]
You should use the new(ish) direct GitHub links for the latest release. E.g. `https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_macOS.zip`
