### ISSUE TITLE
Quoted plugin path issue on 1.0.0 beta

### ISSUE THREAD

**Issue by sudara** [Tracktion/pluginval#79]
It looks like the following won't work on 1.0.0

```
~/Downloads/pluginval-20.app/Contents/MacOS/pluginval --validate "~/Library/Audio/Plug-Ins/Components/Playground.component"
```

Pluginval says it can't find the plugin:

```
Num plugins found: 0
!!! Test 1 failed: No types found. This usually means the plugin binary is missing or damaged, an incompatible format or that it is an AU that isn't found by macOS so can't be created.
FAILED!!  1 test failed, out of a total of 1
*** FAILED
```

Without the quotes it's happy:

```
~/Downloads/pluginval-20.app/Contents/MacOS/pluginval --validate ~/Library/Audio/Plug-Ins/Components/Playground.component
```

This makes it a bit tougher to specify paths with spaces in them, such as:

```
"~/Library/Audio/Plug-Ins/Components/My Plugin.component"
```

(it works with the space escaped by a backslash)

**Comment by jamierpond** [comment]
I'm hitting this on CI, but not locally. Any ideas why this might be the case? (Quotes or no quotes!)

**Comment by sudara** [comment]
Hey there!

What issue are you hitting? "No types found"? 

If so, there are 5 or 6 possible reasons you might run into the issue, check the troubleshooting section of my post for more detail:

https://melatonin.dev/blog/pluginval-is-a-plugin-devs-best-friend/

If you still have trouble, let me know what the command is being run, which platform, and verify the plugin is where you expect it to be...
