### ISSUE TITLE
Handle GitHub's 18.04 runner image deprecation

### ISSUE THREAD

**Issue by sudara** [Tracktion/pluginval#87]
Unfortunately, it looks like like 18.04 is actively being deprecated.

GitHub will actually brownout (periodically fail jobs) during this deprecation period https://github.com/actions/runner-images/issues/6002

Perhaps building on 20.04 would be good enough for backwards compat with 18.04?... I don't have a way of testing this otherwise I'd make the change.

**Comment by drowaudio** [comment]
Unfortunately I don’t think it will. We’ll probably have to go down the Docker route.

that should be straightforward but I was having problems with outdated Git versions in the Docker image last time I tried this.

**Comment by sudara** [comment]
Looks like we might be able to try out the official 18.04 container, might just need some config wrangling to making the container option only kick in for linux... 

https://github.com/actions/runner-images/issues/6002#issuecomment-1211855838

**Comment by drowaudio** [comment]
I don't know if you can see this but I'm trying it out here: https://github.com/Tracktion/pluginval/runs/8089795529?check_suite_focus=true

The problem seems to be that that Docker image has an old version of Git and I'm not sure how to update it. Ideally we'd use a Docker image that was the same as the GitHub Actions one but I don't know if such a thing exists.

**Comment by sudara** [comment]
Should be able to add git to the list of deps and move deps to install before action/checkout. See https://github.com/actions/checkout/issues/238

**Comment by drowaudio** [comment]
I can't see from that thread what the obvious answer is?
I think I tried doing a `sudo apt-get update` but I then got an error saying `sh` isn't recognised or something similar..

**Comment by sudara** [comment]
Sorry, was short because I was on mobile. The bottom of that issue has a "workaround on Ubuntu 18.04" which adds the ppa for git and apt-get installs git. 

Since we're already doing a lot of apt installing, I was suggesting we add the git stuff "Install Linux Deps" step and move that before the actions/checkout step.

However, looks like the linux env will need some more serious setup. For example, sudo isn't installed (I think that's the error you saw, we can just avoid sudo) and neither is `add-apt-repository` and who knows what else.... here's a run in progress with a few things added https://github.com/sudara/pluginval/runs/8095827716?check_suite_focus=true
