### ISSUE TITLE
PluginStateTestRestoration should provide failure detail

### ISSUE THREAD

**Issue by sudara** [Tracktion/pluginval#88]
I have a plugin that is intermittently failing the `PluginStateTestRestoration` test.

The error I get is:

```
Starting tests in: pluginval / Plugin state restoration...
!!! Test 1 failed: Parameters not restored on setStateInformation -- Expected value  within 0.1 of: 134.472, Actual value: 193.868
```

I have 400+ parameters — it would be nice if pluginval could identify the misbehaving params or at least output the expected vs. actual parameter list.

**Comment by drowaudio** [comment]
Fixed here: https://github.com/Tracktion/pluginval/pull/101

**Comment by sudara** [comment]
Yay!
