### ISSUE TITLE
cmake error on Windows

### ISSUE THREAD

**Issue by DesertKnight** [Tracktion/pluginval#96]
The following error on Windows is generated:

c:\p4client\ProAudio\SDKs\PluginVal\1.0.1>cmake -B Builds/Debug -DCMAKE_BUILD_TYPE=Debug . # configure
CMake Error: The source directory "C:/p4client/ProAudio/SDKs/PluginVal/1.0.1/configure" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

cmake used is 3.22

**Comment by DesertKnight** [comment]
Ok. Apparently Windows can not handle "# configure" as a comment. Just need to run without it.

**Comment by drowaudio** [comment]
Yes, sorry, that's really just there to show you what each line is doing.
