### ISSUE TITLE
Plug in error en macos m1

### ISSUE THREAD

**Issue by bernardoveht** [Tracktion/pluginval#99]
Hello I try to use this plug in in waveform 12 and it throws this error

Started validating: /Library/Audio/Plug-Ins/Components/Torpedo Wall Of Sound.component
Random seed: 0x641c305
Validation started
Strictness level: 5

Starting tests in: pluginval / Scan for plugins located in: /Library/Audio/Plug-Ins/Components/Torpedo Wall Of Sound.component...
Num plugins found: 1

Testing plugin: AudioUnit--2f1fd515-35554665
:  v
Completed tests in pluginval / Scan for plugins located in: /Library/Audio/Plug-Ins/Components/Torpedo Wall Of Sound.component

Starting tests in: pluginval / Open plugin (cold)...
!!! Test 1 failed: Expected value: , Actual value: No compatible plug-in format exists for this plug-in
!!! Test 2 failed: Unable to create AudioPluginInstance
FAILED!!  2 tests failed, out of a total of 2

Starting tests in: pluginval / Open plugin (warm)...
!!! Test 1 failed: Expected value: , Actual value: No compatible plug-in format exists for this plug-in
!!! Test 2 failed: Unable to create AudioPluginInstance
FAILED!!  2 tests failed, out of a total of 2
*** FAILED

**Comment by drowaudio** [comment]
This is quite old and sounds like the plugin might not have had a Apple Silicon version at the time of reporting.
